# Generated by Django 4.2.7 on 2023-12-03 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baby', models.IntegerField()),
                ('child', models.IntegerField()),
                ('adult', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('national_id', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('is_vacant', models.BooleanField(default=True)),
                ('price', models.BigIntegerField()),
                ('date_created', models.DateTimeField()),
                ('date_updated', models.DateTimeField()),
                ('capacity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.capacity')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_start_date', models.DateTimeField()),
                ('reservation_end_date', models.DateTimeField()),
                ('customers', models.ManyToManyField(to='main.customer')),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.residence')),
            ],
        ),
    ]
