# Generated by Django 4.2.7 on 2023-12-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='residence',
            old_name='is_vacant',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='residence',
        ),
        migrations.AddField(
            model_name='residence',
            name='reserve',
            field=models.ManyToManyField(to='main.reservation'),
        ),
    ]
